openapi: 3.0.0
info:
  title: MockWebServer
  version: 2.7.3
  description: Servidor de pruebas para los cursos de front-end
servers:
  - url: "http://localhost:4321/api"
    description: Local
paths:
  /blog:
    get:
      summary: Listado de artículos.
      description: Los artículos se pueden filtrar
      parameters:
        - in: query
          name: _page
          description: "Número de página, siendo 0 la primera"
          schema:
            type: integer
            minimum: 0
            default: 0
        - in: query
          name: _rows
          description: Número de filas por página
          schema:
            type: integer
            minimum: 0
            default: 20
      responses:
        "200":
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Blog"
        "500":
          description: "Error interno del servidor"
    post:
      summary: Crear un articulo.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 0
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Articulo"
        required: true
        description: Request Body
      responses:
        "201":
          description: "Articulo creado"
        "500":
          description: "Error interno del servidor"
  "/blog/{id}":
    get:
      summary: Recuperar un articulo.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        "200":
          description: "Articulo encontrado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Articulo"
        "404":
          description: "Articulo no encontrado"
        "500":
          description: "Error interno del servidor"
    put:
      summary: Modificar un articulo.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            minimum: 0
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Articulo"
        required: true
        description: Request Body
      responses:
        "200":
          description: "Articulo modificado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Articulo"
        "404":
          description: "Articulo no encontrado"
        "500":
          description: "Error interno del servidor"
    delete:
      summary: Borrar un articulo.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: "Articulo borrado"
        "404":
          description: "Articulo no encontrado"
        "500":
          description: "Error interno del servidor"
    patch:
      summary: Modificar propiedades de un articulo.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: string
        required: true
        description: Request Body
      responses:
        "200":
          description: "Articulo modificado"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Articulo"
        "404":
          description: "Articulo no encontrado"
        "500":
          description: "Error interno del servidor"
components:
  schemas:
    Articulo:
      type: object
      description: Articulos del blog
      properties:
        id:
          type: integer
          format: int32
          minimum: 0
          description: El 0 actúa como autonumérico en la creación
        titulo:
          type: string
        texto:
          type: string
        autor:
          type: string
        fecha:
          type: string
          format: date
        fotourl:
          type: string
      required:
        - id
        - titulo
    Blog:
      type: array
      items:
        $ref: "#/components/schemas/Articulo"
